### ISSUE TITLE
[Tianjing Jin] Intro the project

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/frontend#4]
First task you will be to check the code repo, find documents, that I've pushed there and please generate some questions. 
Take your time, don't rushing you right now, because jumping in a new project can be a bit challenging.

**Comment by dev-kingdom** [comment]
I'v checked the readme carefully.
The CheckinKyiv project is very exciting for me.
Especially the main idea is very interesting.
There is no problem understanding about List Milestones.
I have some problem about Important Notes.
I would like to learn more about key technologies such as Jest + Enzyme, Netlify, and Travis.
Free Menu Release and others are great.

**Comment by atherdon** [comment]
Ok, Important Notes is the section about tools, that we'll use in our development process. It's ok if you not used them before - i'll  create some tasks and you'll be able to learn it.
Main idea, by using that tools(like tests, error reporting) we'll be able to ship more simple and well-coded product. Later you'll realize how important that tools are in your daily development process, so hopefully soon you'll be addicted to use it ;)
For sure, it will require some time to learn and understand how this things works, but in the end - you'll love it.

**Comment by atherdon** [comment]
#1

**Comment by atherdon** [comment]
i updated the documentation, related to the notes section. hope this will make it more clear
