### ISSUE TITLE
First test assessment [Tianjing Jin]

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/frontend#9]
# Description/Steps to reproduce
Review main task please - #5 

Download this template and convert it into react application
https://www.creative-tim.com/product/full-calendar

# Expected result

# Additional information

**Comment by atherdon** [comment]
Please follow this link: https://github.com/ChickenKyiv/frontend/invitations

**Comment by dev-kingdom** [comment]
I created the fullcalendar - my first assessment in the master branch.
But I've just moved it to "dev-tianjin"-my branch.
I will work in my branch.

**Comment by atherdon** [comment]
ok, thanks

**Comment by atherdon** [comment]
I think we'll start with basics. I'll create a course for you, we'll go step by step.

**Comment by dev-kingdom** [comment]
Hello Arthur.
I've pushed my working project.
I have some problems in progressing my task.
I 've downloaded fullcalendar template from your given URL.
And I've installed fullcalendar-reactwrapper component in my project.
Then I've converted the template to react applications.
In converting, I could not convert jquery functions to react applications.
I've searched for how to do it on google but I didn't search the suitable solutions.
For example, when I convert select javascript function to the onClick event handler, I based in my searched code but it occurs bugs in my project.

      this.state = {
      ...   ....    ....    ....
      this.handleClick = this.handleClick.bind(this);
      ...   ....    ....    ....
      }

      handleClick() {
      var title = prompt('Event Title:');
      if (title) {
            FullCalendar.fullCalendar('renderEvent',
            {
                   title: title,
                   start: start,
                   end: end,
                   allDay: allDay
             },
                true // make the event "stick"
             );
         }
         FullCalendar.fullCalendar('unselect');
      }
I think that I've had some mistake.
These were not pushd in my branch.
Please let me know how to express "$(window).resize(windowResize);" and "$('#external-events div.external-event')" to react.
Please check my working project and give me your advice.
In addition, let me know props, state, and lifecycle in details.
These were not cleared for me.
Thank you.

**Comment by dev-kingdom** [comment]
# My answers to "git+github skills"
## Tell me please what is HEAD thing about?
Long answer to short, I think about HEAD is the list of all branches.
On the other words, HEAD is an endpoint that is pointed the current branch.
So we could use it in undoing previous actions and rewriting git history using working-tree.
For example, we could use git commands such as "git reset filename" and "git reset --hard HEAD^"
We could also use "Head~".
That's all.
## Do you know how to close GitHub issue from git commit?
This question is not clear for me.
I don't know what "close GitHub issue from git commit" is mean.
Maybe by using git command or another, local or online?  
## what is origin?
"Origin" is the parent remote repository of all remote repositories and branches on GitHub.
So in working on the project, origin repository is controlled by CEO.
Other developers create and use other remote repositories.
These are only my opinions.
## how to list all branches inside the repo?
By using git command - "git branch [-a/-r]" we could show both or only one of remote and local branches.

## what difference between fetch and pull
Fetch really only downloads new data from a remote repository.
Fetch is great for getting a fresh view on all things that happened in a remote repository.
Pull, in contrast, is used with a different goal: to update the current HEAD branch with the latest change from the remote server.
## stash tell me more about it
About stashing the dirty state of the working directory, we could use "git stash"- until latest committed.

I think I have many mistakes in my answers and my English expression is not correct.
Please check my answers and let me know your assessment.

**Comment by atherdon** [comment]
ok, starting to reviewing your progress. will post an update soon

**Comment by atherdon** [comment]
#### Git

1) Ok, what will you have in your branch, when you'll run `git reset --hard HEAD`?
2) Just google it :)
3) Check the git docs about origin. partially right.
4) done
5) done
6) Give me more details

**Comment by atherdon** [comment]
Checking your code right now

**Comment by atherdon** [comment]
At first, thank you for your detailed explanation.
No mistakes. This plugin is not well converted to use in react. Which is a bit strange, i think, because it's very popular in Web. But my main goal was to understand your skills and how you'll communicate with me, so this task works well and i'm happy about it. 
Please check this samples and tell me if this will help you.
- https://medium.com/@StartXLabs/how-to-get-react-js-to-work-with-fullcalendar-js-9d4c1270b4b
- https://codepen.io/kotazi/pen/KVoXob

When you'll finish this task i created a simple react course for you. i think this will help you to solve problems with `props`, `states`, etc.
repository with that course is here: https://github.com/GroceriStar/react-only-intern-24

Btw, fix this warning:
```
Compiled with warnings.

./src/components/Calendar.jsx
  Line 2:  'ReactDOM' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

```

**Comment by dev-kingdom** [comment]
Thank you very much.
I'll check that samples and fix that warning.
 And then I will be back soon.

**Comment by dev-kingdom** [comment]
Hi Arthur
I've received the react course.
So I will take the course and I will comment on there my questions.
Do you have any idea?
Please let me know your permission.
Cheers!

**Comment by atherdon** [comment]
Does my solution works? I mean did fullcallendar works well right now?
if you fix issue that you've mentioned before - yes, you can start to work on react course. 
we'll follow the same way as we have here - with tasks and github code commits. But i think after completing that course you'll be more confident with basic things at React and we'll be able to work on current codebase

**Comment by atherdon** [comment]
and tell me if you pushed your changes to your code - want to take a look

**Comment by dev-kingdom** [comment]
Hi Arthur.
I've installed fullcalendar-reactwrapper component for my issues.
How about install react-big-calendar or react-calendar-component?

**Comment by atherdon** [comment]
ok, you can try it at other pages. want to compare and see how it looks


On 14-Jun-2018 at 01:59 PM, Dev Kingdom wrote:


Hi Arthur.
I've installed fullcalendar-reactwrapper component for my issues.
How about install react-big-calendar or react-calendar-component?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/frontend/issues/9#issuecomment-397305862>,
or mute the thread

**Comment by dev-kingdom** [comment]
I've pushed my fullcalendar project in "dev-tianjing" branch.
I've inserted Test Event to test how to trigger event.
In my project, the events in Fullcalendar component doesn't happen.
But in my test curly, the event has happened.
And then in the render function, how to deal the jquery syntax?
To solve this problem, I've installed jquery component and import it in the Calendar component.
Please solve these problems.

**Comment by dev-kingdom** [comment]
I'm sorry for my English expression.
Would you please help these problems?
I am happy if you say "OK".
Thank you very much.

**Comment by atherdon** [comment]
Don't worry about your English skills. I'm not a native speaker. When i just started code - my skills was very bad. but practice give me this chance to chat with you right now :)

**Comment by atherdon** [comment]
please check this approach from our plugin. maybe stuff from componentMount  method will help you? if no - i'll keep looking for solutions too

**Comment by dev-kingdom** [comment]
Hi Arthur.
I checked the fullcalendar-reactWrapper plugin.
I fixed some warnings and I inserted select event handler.
But I didn't catch"prevprops" and "nextprops".
And I didn't transfer "prevstate" to "nextstate".
Actually, I am not sure about mounting state and updating props.
I've just pushed my fullcalendar project in "dev-tianjing" branch.
Please check my project and help me with these problems.
Thank you.

**Comment by atherdon** [comment]
share it with me


On 16-Jun-2018 at 02:27 PM, tianjing jin wrote:


Hi Arthur.
I've created my own git account.
Please let me know what should I do next?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/frontend/issues/9#issuecomment-397815854>,
or mute the thread

**Comment by dev-tianjing** [comment]
Hi Arthur.
This is my invite link URL.
https://github.com/dev-tianjing/dev-tianjing/invitations

**Comment by dev-tianjing** [comment]
Hi  Arthur
I've just completed my first assessment. 
I installed moment component and get and set Event times by using it.
I pushed my complete project in "dev-tianjing" branch.
Please check my project and let me know your advice.
I will work on react-only-intern-24 and let me know you my progress.
Thank you very much.
